osx_image: xcode8
language: objective-c

before_install:
- gem install xcpretty
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- travis_wait 25 pod repo update --silent
- pod install

script:
- xcodebuild clean build -workspace Tailor.xcworkspace -scheme Tailor-iOS -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace Tailor.xcworkspace -scheme Tailor-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty
- xcodebuild clean build -workspace Tailor.xcworkspace -scheme Tailor-Mac -sdk macosx | xcpretty
- xcodebuild test -workspace Tailor.xcworkspace -scheme Tailor-Mac -sdk macosx | xcpretty

notifications:
  email: false
