osx_image: xcode8.2
language: objective-c

cache:
  directories:
    - Carthage

before_install:
  - travis_wait 35; bin/bootstrap-if-needed

script:
  - xcodebuild clean
  - xcodebuild clean build -project Tailor.xcodeproj -scheme Tailor-iOS -sdk iphonesimulator | xcpretty
  - xcodebuild test -project Tailor.xcodeproj -scheme Tailor-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.2' | xcpretty
  - xcodebuild clean build -project Tailor.xcodeproj -scheme Tailor-Mac -sdk macosx | xcpretty
  - xcodebuild test -project Tailor.xcodeproj -scheme Tailor-Mac -sdk macosx | xcpretty

notifications:
  email: false
