osx_image: xcode8.2
language: objective-c

cache:
  directories:
    - Carthage

before_install:
  - travis_wait 35; bin/bootstrap-if-needed

script:
- xcodebuild clean build -workspace Tailor.xcworkspace -scheme Tailor-iOS -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace Tailor.xcworkspace -scheme Tailor-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty
- xcodebuild clean build -workspace Tailor.xcworkspace -scheme Tailor-Mac -sdk macosx | xcpretty
- xcodebuild test -workspace Tailor.xcworkspace -scheme Tailor-Mac -sdk macosx | xcpretty

notifications:
  email: false
